services:
  devpi:
    restart: always
    build: ./devpi
    expose:
      - 4040
    volumes:
      - server:/devpi/server
      - server-upgrade:/devpi/server-upgrade

  nginx:
    restart: always
    build: ./nginx
    ports:
      - 80:8080
    volumes_from:
      - devpi

volumes:
  server:
  server-upgrade:
